<a href="https://colab.research.google.com/github/roopasneha/assignment_1/blob/main/AssignmentNumpy_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [2]:
print(np.__version__)
print(np.show_config())

1.21.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [24]:
x=np.zeros(10)
print(x)

[0. 0. 0. ... 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [25]:
x=np.array([4,4])

print(x.size*x.itemsize)

16


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [26]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [27]:
x=np.zeros(10)
x[4]=1
print(x)

[0. 0. 0. ... 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [28]:
x=np.arange(10,49)
print(x)

[10 11 12 ... 46 47 48]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [30]:
x=np.arange(10,49)
x=x[::-1]
print(x)

[48 47 46 ... 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [31]:
x=np.arange(9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [32]:
x=np.array([1,2,0,0,4,0])
np.nonzero(x==0)[0] 

array([2, 3, 5])

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [33]:
array2D=np.eye(3)

print(array2D)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [34]:
array=np.random.random((3,3,3))

print(array)

[[[0.85939535 0.32197511 0.89069234]
  [0.9572857  0.14509146 0.19792175]
  [0.60179111 0.52001892 0.66184304]]

 [[0.1428937  0.68821063 0.87084032]
  [0.18339815 0.10661131 0.65150244]
  [0.08197124 0.31858273 0.39710733]]

 [[0.77258208 0.33063974 0.22152182]
  [0.48319721 0.28548046 0.14041088]
  [0.885367   0.13190754 0.29369201]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [35]:
x=np.random.random((10,10))
print(np.min(x))
print(np.max(x))

0.002000598437422285
0.9861370501043033


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [36]:
x=np.random.random((5,6))
np.mean(x)

0.4846183786503161

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [37]:
x=np.ones((6,6))
x[1:-1,1:-1]=0
print(x)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [38]:
x=np.ones((5,5))
x=np.pad(x,pad_width=1,mode='constant',constant_values=0)
print(x)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 1. 1. ... 1. 1. 0.]
 [0. 1. 1. ... 1. 1. 0.]
 ...
 [0. 1. 1. ... 1. 1. 0.]
 [0. 1. 1. ... 1. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [39]:
print(0*np.nan)
print(np.nan==np.nan)
print(np.inf>np.nan)
print(np.nan-np.nan)
print(0.3==3*0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [40]:
x=np.diag(1+np.arange(4),k=-1)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [41]:
x=np.zeros((8,8),dtype=int)
x[1::2,::2]=1
x[::2,1::2]=1
print(x)


[[0 1 0 ... 1 0 1]
 [1 0 1 ... 0 1 0]
 [0 1 0 ... 1 0 1]
 ...
 [1 0 1 ... 0 1 0]
 [0 1 0 ... 1 0 1]
 [1 0 1 ... 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [42]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [43]:
x=np.tile(np.array([[0,1],[1,0]]),(4,4))
print(x)

[[0 1 0 ... 1 0 1]
 [1 0 1 ... 0 1 0]
 [0 1 0 ... 1 0 1]
 ...
 [1 0 1 ... 0 1 0]
 [0 1 0 ... 1 0 1]
 [1 0 1 ... 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [44]:
x=np.random.random((5,5))
xmax,xmin = x.max(),x.min()
x=(x-xmin)/(xmax-xmin)
print(x)

[[0.32008606 0.74654707 0.81589729 0.76049962 0.8505614 ]
 [0.25707767 0.85439966 0.42102925 0.01795489 0.85118105]
 [0.81895488 0.9954309  0.20881095 0.93287066 0.19389045]
 [0.99620781 0.562818   0.67175513 0.62815478 0.64003524]
 [1.         0.5948445  0.53799543 0.40036608 0.        ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [45]:
color=np.dtype([("r",np.ubyte),
                ("g",np.ubyte),
                ("b",np.ubyte),
                ("a",np.ubyte)])
print(color)


[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [46]:
x=np.dot(np.ones((5,3)),np.ones((3,2)))
print(x)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [48]:
x=np.ones((5,3)) @ np.ones((3,2))
print(x)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [47]:
x=np.arange(11)
x[(3<x) & (x<8)] *=-1
print(x)

[ 0  1  2 ...  8  9 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [49]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [50]:
z=1
z**z
2<<z>>2
z<-z
1j*z
z/1/1
z<z>z

False

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [51]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [52]:
x=np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(x)),x))

#less efficient
print(np.where(x>0, np.ceil(x), np.floor(x)))

[ 1. -3.  9. ... -4. -3. -3.]
[ 1. -3.  9. ... -4. -3. -3.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [53]:
x1=np.random.randint(0,10,10)
x2=np.random.randint(0,10,10)
print(np.intersect1d(x1,x2))

[2 6 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [54]:
#suicide mode on
defaults=np.seterr(all="ignore")
x=np.ones(1)/0
#back to sanity
_=np.seterr(**defaults)

#equivalently with a context manager
with np.errstate(all="ignore"):
  np.arange(3)/0


#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [55]:
np.sqrt(-1) == np.emath.sqrt(-1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [56]:
yesterday=np.datetime64('today')-np.timedelta64(1)
today=np.datetime64('today')
tomorrow=np.datetime64('today')+np.timedelta64(1)
print(yesterday)
print(today)
print(tomorrow)

2022-04-08
2022-04-09
2022-04-10


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [57]:
x=np.arange('2016-07' , '2016-08', dtype='datetime64[D]')
print(x)

['2016-07-01' '2016-07-02' '2016-07-03' ... '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [58]:
a=np.ones(3)*1
b=np.ones(3)*2
np.add(a,b,out=b)
np.divide(a,2,out=a)
np.negative(a,out=a)
np.multiply(a,b,out=a)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [59]:
z=np.random.uniform(0,10,10)
print(z-z%1)
print(z//1)
print(np.floor(z))
print(z.astype(int))
print(np.trunc(z))

[4. 6. 5. ... 9. 6. 1.]
[4. 6. 5. ... 9. 6. 1.]
[4. 6. 5. ... 9. 6. 1.]
[4 6 5 ... 9 6 1]
[4. 6. 5. ... 9. 6. 1.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [60]:
x=np.zeros((5,5))
x +=np.arange(5)
print(x)

#WITHOUT BROADCASING
x=np.tile(np.arange(0,5),(5,1))
print(x)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [61]:
def generate():
  for x in range(10):
    yield x
y=np.fromiter(generate(),dtype=float,count=-1)
print(y)

[0. 1. 2. ... 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [62]:
x=np.linspace(0,1,11,endpoint=False)[1:]
print(x)

[0.09090909 0.18181818 0.27272727 ... 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [63]:
x=np.random.random(10)
x.sort()
print(x)

[0.11828121 0.23239302 0.29312256 ... 0.56563759 0.81900556 0.91516367]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [65]:
x=np.arange(10)
np.add.reduce(z)

53.95059413639703

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [64]:
a=np.random.randint(0,2,5)
b=np.random.randint(0,2,5)

#comparsion of values
equal=np.allclose(a,b)
print(equal)

#values have to be exactly equal
equal=np.array_equal(a,b)
print(equal)

False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [66]:
import numpy as np
x = np.zeros(10)
x.flags.writeable = False
x[0]=[1]

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [67]:
z=np.random.random((10,2))
x,y = z[:,0], z[:,1]
r=np.sqrt(x**2+y**2)
t=np.arctan2(y,x)
print(r)
print(t)

[0.1727907  0.70180002 0.99492519 ... 0.62542431 1.1169235  0.75652309]
[0.8867055  0.88564156 0.7671515  ... 1.37210693 0.72318618 1.50309832]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [68]:
x=np.random.random(10)
x[x.argmax()]=0
print(z)

[[0.10919831 0.13391175]
 [0.44409404 0.54341858]
 [0.71623739 0.69056509]
 ...
 [0.12344918 0.61311979]
 [0.83735866 0.73915396]
 [0.051176   0.75479018]]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [69]:
z=np.zeros((5,5),[('x',float),('y',float)])
z['x'],z['y']=np.meshgrid(np.linspace(0,1,5),
                          np.linspace(0,1,5))
print(z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [70]:
x=np.arange(8)
y=x+0.5
c=1.0 / np.subtract.outer(x,y)
print(np.linalg.det(c))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [71]:
for dtype in [np.int8, np.int32,np.int64]:
  print(np.iinfo(dtype).min)
  print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
  print(np.finfo(dtype).min)
  print(np.finfo(dtype).max)
  print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [72]:
np.set_printoptions(threshold=float())
x=np.zeros((4,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [73]:
z=np.arange(100)
v=np.random.uniform(0,100)
index=(np.abs(z-v)).argmin()
print(z[index])

24


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [74]:
z=np.zeros(10,[ ('position',[('x',float,1),
                            ('y',float,1)]),
                ('color',   [('r',float,1),
                             ('g',float,1),
                             ('b',float,1)])])
print(z)
           

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ... ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [17]:
z=np.random.random((100,2))
x,y=np.atleast_2d(z[:,0]) , (z[:,1])
d=np.sqrt((x-x.T)**2+(y-y.T)**2)
print(d)

[[0.         0.15754013 0.33253963 ... 0.26259376 0.00371824 0.29030886]
 [0.15754013 0.         0.1749995  ... 0.10505363 0.15382188 0.13276873]
 [0.33253963 0.1749995  0.         ... 0.06994587 0.32882138 0.04223077]
 ...
 [0.26259376 0.10505363 0.06994587 ... 0.         0.25887552 0.0277151 ]
 [0.00371824 0.15382188 0.32882138 ... 0.25887552 0.         0.28659062]
 [0.29030886 0.13276873 0.04223077 ... 0.0277151  0.28659062 0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [75]:
z=(np.random.rand(10)*100).astype(np.float32)
y=z.view(np.int32)
y[:]=z
print(y)

[26 26 36 ...  0 82 48]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [76]:
from io import StringIO
s=StringIO('''1,2,3,4,5
           6, , ,7,8
            , ,9,10,11
''')  
z=np.genfromtxt(s, delimiter=",",dtype=np.int) 
print(z)       

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [77]:
z=np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(z):
  print(index, value)
for index in np.ndindex(z.shape):
  print(index, z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [78]:
x,y=np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
d=np.sqrt(x*x+y*y)
sigma, mu=1.0,0.0
g=np.exp(-((d-mu)**2 / (2.0 * sigma**2 )))
print(g)

[[0.36787944 0.44822088 0.51979489 ... 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 ... 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 ... 0.73444367 0.63331324 0.51979489]
 ...
 [0.51979489 0.63331324 0.73444367 ... 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 ... 0.63331324 0.54610814 0.44822088]
 [0.36787944 0.44822088 0.51979489 ... 0.51979489 0.44822088 0.36787944]]


#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [79]:
n=10
p=3
z=np.zeros((n,n))
np.put(z,np.random.choice(range(n*n), p, replace=False),1)
print(z)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [80]:
x=np.random.rand(5,10)

#recent versions of numpy
y=x-x.mean(axis=1, keepdims=True)

#older versions of numpy
y=x-x.mean(axis=1).reshape(-1,1)

print(y)

[[-0.16203177  0.45126613 -0.27880607 ... -0.01452501 -0.15055828
   0.43526284]
 [-0.34864758 -0.29292694 -0.27439435 ...  0.48772833 -0.03100731
   0.18750436]
 [-0.05501596 -0.63897828 -0.02045569 ...  0.23100879  0.13663334
   0.1298232 ]
 [-0.22047936 -0.3682854  -0.46830905 ...  0.38939095 -0.44317353
   0.50040794]
 [ 0.18371091  0.38166957 -0.22071402 ... -0.51747127 -0.28193557
   0.24717354]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [81]:
x=np.random.randint(0,10,(3,3))
print(x)
print(x[x[:,1].argsort()])

[[1 9 2]
 [3 9 1]
 [8 2 5]]
[[8 2 5]
 [1 9 2]
 [3 9 1]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [82]:
z=np.random.randint(0,3,(3,10))
print((~z.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [83]:
X=np.random.uniform(0,1,10)
x=0.5
m=X.flat[np.abs(X-x).argmin()]
print(m)

0.43979842753504517


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [84]:
a=np.arange(3).reshape(3,1)
b=np.arange(3).reshape(1,3)
it=np.nditer([a,b,None])
for x,y,z in it: z[...] = x+y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [85]:
class NameArray(np.ndarray):
  def __new__(cls, array, name="no name"):
    obj = np.asarray(array).view(cls)
    obj.name = name
    return obj
  def __array_finalize__(self, obj):
    if obj is None: return
    self.info = getattr(obj, 'name', "no name")

x=NameArray(np.arange(10), "range_10")
print(x.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [86]:
z=np.ones(10)
i=np.random.randint(0,len(z),20)
z += np.bincount(i, minlength=len(z))
print(z)

#another solution
np.add.at(z,i,1)
print(z)

[2. 4. 3. ... 2. 2. 4.]
[3. 7. 5. ... 3. 3. 7.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [87]:
x=[1,2,3,4,5,6]
i=[1,3,9,3,4,1]
F=np.bincount(i,x)
print(F)

[0. 7. 0. ... 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [88]:
w, h=256, 256
I=np.random.randint(0,4,(h,w,3)).astype(np.ubyte)
colors=np.unique(I.reshape(-1,3),axis=0)
n=len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [89]:
a=np.random.randint(0,10,(3,4,3,4))
#tuple of axes
sum=a.sum(axis=(-2,-1))
print(sum)
#solution by flattering the last two dimensions into one
sum=a.reshape(a.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[57 47 55 42]
 [43 50 58 68]
 [49 55 69 51]]
[[57 47 55 42]
 [43 50 58 68]
 [49 55 69 51]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [90]:
d = np.random.uniform(0,1,100)
s = np.random.randint(0,10,100)
d_sums = np.bincount(s,weights=d)
d_counts = np.bincount(s)
d_means = d_sums / d_counts
print(d_means)

[0.44972036 0.67772671 0.5360299  ... 0.58320001 0.37902994 0.63342238]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [91]:
a=np.random.uniform(0,1,(5,5))
b=np.random.uniform(0,1,(5,5))

#slow version
np.diag(np.dot(a,b))
#fast version
np.sum(a*b.T, axis=1)
#faster version
np.einsum("ij,ji->", a, b)

5.121682435911616

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [92]:
z=np.array([1,2,3,4,5])
nz=3
x=np.zeros(len(z)+(len(z)-1)*(nz))
x[::nz+1]=z
print(x)

[1. 0. 0. ... 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [93]:
a=np.ones((5,5,3))
b=2*np.ones((5,5))
print(a * b[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [94]:
a=np.arange(25).reshape(5,5)
a[[0,1]]=a[[1,0]]
print(a)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [95]:
faces=np.random.randint(0,100,(10,3))
F=np.roll(faces.repeat(2,axis=1),-1,axis=1)
F=F.reshape(len(F)*3,2)
F=np.sort(F,axis=1)
G=F.view(dtype=[('p0',F.dtype),('p1',F.dtype)])
G=np.unique(G)
print(G)

[( 3, 29) ( 3, 87) ( 4,  5) ... (66, 73) (69, 86) (93, 96)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [96]:
c=np.bincount([1,1,2,3,4,4,6])
a=np.repeat(np.arange(len(c)),c)
print(a)


[1 1 2 ... 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [97]:
def moving_average(a, n=3):
  ret=np.cumsum(a,dtype=float)
  ret[n:]=ret[n:] - ret[:-n]
  return ret[n-1:] / n
z=np.arange(20)
print(moving_average(z, n=3))

[ 1.  2.  3. ... 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [98]:
from numpy.lib import stride_tricks

def rolling(a,window):
  shape = (a.size - window + 1,window)
  strides = (a.strides[0], a.strides[0])
  return stride_tricks.as_strided(a, shape=shape, strides=strides)
z=rolling(np.arange(10),3)
print(z) 


[[0 1 2]
 [1 2 3]
 [2 3 4]
 ...
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [99]:
z=np.random.randint(0,2,100)
np.logical_not(z, out=z)

z=np.random.uniform(-1.0,1.0,100)
np.negative(z,out=z)

array([ 0.76169833, -0.4363634 , -0.20416832, ...,  0.58802161,
        0.94395267, -0.03921972])

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [101]:
def distance(P0, P1, p):
  T=P1-P0
  L=(T**2).sum(axis=1)
  U = -((P0[:,0]-p[...,0])*T[:,0]+(P0[:,1]-p[...,1])*T[:,1]) / L
  D = P0 +(U*T) - p
  return np.sqrt((D**2).sum(axis=1))

P0=np.random.uniform(-10,10,(10,2))
P1=np.random.uniform(-10,10,(10,2))
p=np.random.uniform(-10,10,(1,2))
print(distance(P0, P1, p))

ValueError: ignored

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [122]:
P0=np.random.uniform(-10,10,(10,2))
P1=np.random.uniform(-10,10,(10,2))
p=np.random.uniform(-10,10,(1,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

ValueError: ignored

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [22]:
Z=np.random.randint(0,10,(10,10))
shape=(5,5)
fill=0
position=(1,1)

R=np.ones(shape, dtype=Z.dtype)*fill
P=np.array(list(position)).astype(int)
Rs=np.array(list(R.shape)).astype(int)
Zs=np.array(list(Z.shape)).astype(int)

R_start=np.zeros((len(shape),)).astype(int)
R_stop=np.array(list(shape)).astype(int)
Z_start=(P-Rs//2)
Z_stop=(P+Rs//2)+Rs%2

R_start=(R_start - np.minimum(Z_start,0)).tolist()
Z_start=(np.maximum(Z_start,0)).tolist()
R_stop=np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop=(np.minimum(Z_stop,Zs)).tolist()

r=[slice(start,stop) for start,stop in zip(R_start,R_stop)]
z=[slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r]=Z[z]
print(Z)
print(R)


[[9 1 1 ... 4 6 4]
 [6 9 5 ... 2 8 1]
 [0 1 4 ... 3 8 4]
 ...
 [2 4 7 ... 8 2 2]
 [3 0 9 ... 4 7 5]
 [7 3 4 ... 4 9 9]]
[[0 0 0 0 0]
 [0 9 1 1 2]
 [0 6 9 5 6]
 [0 0 1 4 5]
 [0 3 4 1 1]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [102]:
from numpy.lib.stride_tricks import sliding_window_view
z=np.arange(1,15,dtype=np.uint32)
r=stride_tricks.as_strided(z,(11,4),(4,4))
print(r)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 ...
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [103]:
x=np.random.uniform(0,1,(10,10))
u,s,v=np.linalg.svd(x)
rank=np.sum(s > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [104]:
x=np.random.randint(0,10,50)
print(np.bincount(z).argmax())

1


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [105]:
z=np.random.randint(0,5,(10,10))
n=3
i=1+(z.shape[0]-3)
j=1+(z.shape[1]-3)
c=stride_tricks.as_strided(z,shape=(i,j,n,n),strides=z.strides + z.strides)
print(c)

[[[[0 4 1]
   [0 3 0]
   [1 4 3]]

  [[4 1 2]
   [3 0 2]
   [4 3 0]]

  [[1 2 4]
   [0 2 0]
   [3 0 2]]

  ...

  [[4 3 4]
   [2 4 2]
   [4 0 0]]

  [[3 4 1]
   [4 2 1]
   [0 0 2]]

  [[4 1 4]
   [2 1 2]
   [0 2 4]]]


 [[[0 3 0]
   [1 4 3]
   [1 4 3]]

  [[3 0 2]
   [4 3 0]
   [4 3 1]]

  [[0 2 0]
   [3 0 2]
   [3 1 4]]

  ...

  [[2 4 2]
   [4 0 0]
   [4 0 4]]

  [[4 2 1]
   [0 0 2]
   [0 4 1]]

  [[2 1 2]
   [0 2 4]
   [4 1 1]]]


 [[[1 4 3]
   [1 4 3]
   [1 4 0]]

  [[4 3 0]
   [4 3 1]
   [4 0 0]]

  [[3 0 2]
   [3 1 4]
   [0 0 4]]

  ...

  [[4 0 0]
   [4 0 4]
   [0 3 4]]

  [[0 0 2]
   [0 4 1]
   [3 4 0]]

  [[0 2 4]
   [4 1 1]
   [4 0 4]]]


 ...


 [[[3 0 3]
   [1 3 4]
   [0 2 2]]

  [[0 3 0]
   [3 4 4]
   [2 2 1]]

  [[3 0 2]
   [4 4 2]
   [2 1 4]]

  ...

  [[2 3 1]
   [4 4 0]
   [3 2 3]]

  [[3 1 4]
   [4 0 2]
   [2 3 2]]

  [[1 4 4]
   [0 2 2]
   [3 2 0]]]


 [[[1 3 4]
   [0 2 2]
   [4 2 3]]

  [[3 4 4]
   [2 2 1]
   [2 3 0]]

  [[4 4 2]
   [2 1 4]
   [3 0 3]]

  ...

  [[4

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [106]:
class Symetric(np.ndarray):
  def __setitem__(self, index, value):
    i,j = index
    super(Symetric, self).__setitem__((i,j), value)
    super(Symetric, self).__setitem__((j,i), value)

def symetric(z):
  return np.asarray(z+z.T -np.diag(z.diagonal())).view(Symetric)

s=symetric(np.random.randint(0,10,(5,5)))
s[2,3]=42
print(s)

[[ 4  6  4 15  3]
 [ 6  3  8  3 14]
 [ 4  8  5 42  0]
 [15  3 42  0 10]
 [ 3 14  0 10  8]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [107]:
p, n=10,20
m=np.ones((p,n,n))
v=np.ones((p,n,1))
s=np.tensordot(m, v,axes=[[0,2],[0,1]])
print(s)

[[200.]
 [200.]
 [200.]
 ...
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [108]:
x=np.ones((16,16))
k=4
s=np.add.reduceat(np.add.reduceat(x, np.arange(0, x.shape[0], k), axis=0),
                                     np.arange(0, x.shape[1], k), axis=1)
print(s)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]



#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [109]:
def iterate(Z):
  N=(Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:]+
     Z[1:-1,0:-2]                + Z[1:-1,2:]+
     Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])
  #RULES
  birth=(N==3) & (Z[1:-1,1:-1]==0)
  survive=((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
  Z[...]=0
  Z[1:-1,1:-1][birth | survive] = 1
  return Z

Z=np.random.randint(0,2,(50,50))
for i in range(100): Z=iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [110]:
x=np.arange(10000)
np.random.shuffle(x)
n=5

#slow
print(x[np.argsort(x)[-n:]])

#fast
print(x[np.argpartition(-x,n)[:n]])

[9995 9996 9997 9998 9999]
[9998 9999 9996 9997 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [111]:
def cartesian(arrays):
  arrays=[np.asarray(a) for a in arrays]
  shape=(len(x) for x in arrays)

  ix=np.indices(shape, dtype=int)
  ix=ix.reshape(len(arrays), -1).T

  for n, arr in enumerate(arrays):
    ix[:, n]=arrays[n][ix[:,n]]

  return ix
print(cartesian(([1,2,3], [4,5], [6,7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 ...
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [112]:
x=np.array([("Hello", 2.5, 3),
            ("World", 3.6, 2)])
r=np.core.records.fromarrays(x.T,
                             names = 'col1,col2,col3',
                             formats='S8, f8, i8')
print(r)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [113]:
x= np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

1 loop, best of 5: 3.73 s per loop
10 loops, best of 5: 148 ms per loop
10 loops, best of 5: 127 ms per loop


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [114]:
a=np.random.randint(0,5,(8,3))
b=np.random.randint(0,5,(2,2))

c=(a[..., np.newaxis, np.newaxis] == b)
rows=np.where(c.any((3,1)).all(1))[0]
print(rows)

[2 3 6]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [115]:
x=np.random.randint(0,5,(10,3))
print(x)
#solution for arrays of all dtypes(including string and record arrays)
e=np.all(x[:,1:] == x[:,:-1], axis=1)
u=x[~e]

#solution for numerical arrays only
u=x[x.max(axis=1) != x.min(axis=1),:]
print(u)

[[2 0 4]
 [3 2 1]
 [1 4 3]
 ...
 [0 2 1]
 [3 1 2]
 [0 1 0]]
[[2 0 4]
 [3 2 1]
 [1 4 3]
 ...
 [0 2 1]
 [3 1 2]
 [0 1 0]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [116]:
x=np.array([0,1,2,3,15,16,32,64,128])
y=((x.reshape(-1,1) & (2**np.arange(8))) !=0).astype(int)
print(y[:,::-1])

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 1 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [117]:
x=np.random.randint(0,2,(6,3))
T=np.ascontiguousarray(x).view(np.dtype((np.void,x.dtype.itemsize * x.shape[1])))
_, idx=np.unique(T, return_index=True)
ux=x[idx]
print(ux)

[[0 0 0]
 [0 0 1]
 [0 1 1]
 [1 0 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [118]:
a=np.random.uniform(0,1,10)
b=np.random.uniform(0,1,10)

np.einsum('i->',a)#sum
np.einsum('i,i->i', a, b)#a*b
np.einsum('i,i', a, b)#inner
np.einsum('i,j->ij', a, b)#outer

array([[2.67901808e-02, 5.90403472e-01, 2.59007626e-01, ...,
        5.46772130e-01, 4.29705806e-01, 5.61187439e-01],
       [2.88141950e-02, 6.35008809e-01, 2.78575807e-01, ...,
        5.88081092e-01, 4.62170337e-01, 6.03585487e-01],
       [1.47493774e-04, 3.25047588e-03, 1.42597068e-03, ...,
        3.01026282e-03, 2.36575227e-03, 3.08962653e-03],
       ...,
       [3.56533180e-02, 7.85729776e-01, 3.44696488e-01, ...,
        7.27663646e-01, 5.71867650e-01, 7.46848048e-01],
       [1.70471531e-02, 3.75686093e-01, 1.64811976e-01, ...,
        3.47922557e-01, 2.73430803e-01, 3.57095319e-01],
       [4.12801540e-02, 9.09734295e-01, 3.99096772e-01, ...,
        8.42504121e-01, 6.62120273e-01, 8.64716221e-01]])

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [119]:
phi=np.arange(0, 10*np.pi, 0.1)
a=1
x=a*phi*np.cos(phi)
y=a*phi*np.sin(phi)

dr=(np.diff(x)**2 + np.diff(y)**2)**.5
r=np.zeros_like(x)
r[1:]=np.cumsum(dr)
r_int=np.linspace(0, r.max(), 200)
x_int=np.interp(r_int, r, x)
y_int=np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [120]:
x=np.asarray([[1.0, 0.0, 3.0, 8.0],
              [2.0, 0.0, 1.0, 1.0],
              [1.5, 2.5, 1.0, 0.0]])
n=4
m=np.logical_and.reduce(np.mod(x, 1) == 0, axis=-1)
m &= (x.sum(axis=-1) == n)
print(x[m])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [121]:
X=np.random.randn(100)
n=1000
idx=np.random.randint(0, X.size, (n, X.size))
means=X[idx].mean(axis=1)
confint=np.percentile(means, [2.5,97.5])
print(confint)

[-0.32647887  0.07120272]
